#! /usr/bin/env bash
DATA_DIR=$(readlink -f ~)"/.gdait/data";
mkdir -p "$DATA_DIR"
# LINKS
ROUTES_LINK="http://91.244.248.19/dataset/c24aa637-3619-4dc2-a171-a23eec8f2172/resource/4128329f-5adb-4082-b326-6e1aea7caddf/download/routes.json"
STOPS_LINK="http://91.244.248.19/dataset/c24aa637-3619-4dc2-a171-a23eec8f2172/resource/cd4c08b5-460e-40db-b920-ab9fc93c1a92/download/stops.json";
STOPS_IN_TRIPS_LINK="http://91.244.248.19/dataset/c24aa637-3619-4dc2-a171-a23eec8f2172/resource/0f2de200-e78b-4183-ae0d-071d7f07fc3f/download/stopsintrips.json"

today=$(date '+%Y-%m-%d');
jq_filter_lines="[.[\"$today\"] | .routes[] | select(.agencyId == 2 or .agencyId == 1)]";
jq_filter_stops="[.[\"$today\"] | .stops[]  | select(.virtual == 0 and .nonpassenger == 0)]";
jq_filter_stopsInTrips="[.[\"$today\"] | .stopsInTrip[] | select(.agencyId == 2 or .agencyId == 1)]";

echo "[GDAIT] - aktualizacja danych"
echo "Pobieram trasy...";
curl -s "$ROUTES_LINK" | jq -c "$jq_filter_lines" > "$DATA_DIR/routes" 
echo "Pobieram przystanki...";
curl -s "$STOPS_LINK" | jq -c "$jq_filter_stops" > "$DATA_DIR/stops"
echo "Pobieram przystanki wg tras...";
curl -s "$STOPS_IN_TRIPS_LINK" | jq -c "$jq_filter_stopsInTrips" > "$DATA_DIR/stopsintrip" | pv
echo "$today" | cat > $DATA_DIR/timestamp;

