#! /usr/bin/env bash
DATA_DIR=$(readlink -f ~)"/.gdait/data";
DATA_STOPS="$DATA_DIR/stops";
DATA_STOPSINTRIP="$DATA_DIR/stopsintrip";
DATA_ROUTES="$DATA_DIR/routes";
today=$(date '+%Y-%m-%d');
now=$(date '+%Y-%m-%d %H:%M');

jq_filter_lines="[.[] | select(.agencyId == 2 or .agencyId == 1)]";
jq_filter_stops="[.[] | select(.stopDesc | match(\"$STOP_QUERY\";\"i\"))]";


jq_print_lines='.[] | .routeShortName+": "+.routeLongName';

# $1 line full name 
function get_line_id_by_name(){
# cat "$DATA_ROUTES" | jq -r "$jq_filter_lines" | jq ".[] | select(.routeShortName | match(\"$1\";\"i\")) | .routeId"
cat "$DATA_ROUTES" | jq -r "$jq_filter_lines" | jq ".[] | select(.routeShortName == \"$1\") | .routeId"
}
function get_line_name_by_id(){
cat "$DATA_ROUTES" | jq -r "$jq_filter_lines" | jq ".[] | select(.routeId == \"$1\") | .routeShortName"
}
function list_lines(){
cat "$DATA_ROUTES" | jq -r "$jq_filter_lines" | jq "$jq_output_format_lines";
}
function get_stops_by_name(){
	local jq_filter_stops="[.[] | select(.stopDesc | match(\"$1\";\"i\"))]";
	cat "$DATA_STOPS" | jq -r "$jq_filter_stops"
}
function get_stop_by_name(){
	local jq_filter_stops=".[] | select(.stopDesc | match(\"$1\";\"i\")) | .stopId";
	cat "$DATA_STOPS" | jq -r -S "$jq_filter_stops"
}
function get_stop_name_by_id(){
	local jq_filter_stops=".[]  | select(.stopId == $1) | .stopDesc+\" \"+.subName";
	cat "$DATA_STOPS" | jq -r "$jq_filter_stops"
}

function get_stop_by_line(){
	local jq_filter_stopsintrip=".[] | select(.routeId == $1 and .stopId == $2) | .stopId";
	cat "$DATA_STOPSINTRIP" | jq -r -S "$jq_filter_stopsintrip"
}
# $1 stopId
# $2 routeId
function delay_by_stop_and_line(){
	local stop_header=$(get_stop_name_by_id $1);
	local jq_format_delay='.[] | "  -  "+.estimatedTime+" =>  "+.headsign+" "';
	local delays=$(curl -s "http://87.98.237.99:88/delays?stopId=$1" | jq "[.delay[] | select(.routeId == $2)]" | jq -r "$jq_format_delay");
	[ -z "$delays" ] || echo "$stop_header";
	[ -z "$delays" ] || echo "$delays";

}
function fetch_data_if_needed(){
./gdait-data
}

# $1 line name
# $2 stop name part
function get_delays(){
found_stops=$(get_stop_by_name "$2");
found_lines=$(get_line_id_by_name "$1");
for lineId in $found_lines;do
echo "GDAIT - odjazdy lini $1"
echo "$now"
	for foundStop in $found_stops;do
	line_stops=$(get_stop_by_line $lineId $foundStop | uniq);
		for lineStop in $line_stops;do
		 delay_by_stop_and_line $lineStop $lineId
		done
	done
done
}
function usage(){
	echo 'Użycie: '$0' <linia> <przystanek>
	
	linia       - pełna nazwa/nr linii, np. N12, 227, 8
	przystanek  - fragment nazwy przystanku (z polskimi znakami i spacjami)

	Przykłady:
			gdait N12 "dworzec główny"
			gdait 8 oliw
	'
}
usage